#!/usr/bin/env python3
"""
EMG Gesture Threshold Calibration

Analyzes recorded resting and active EMG periods to estimate optimal
gesture detection thresholds. Outputs recommended configuration for firmware.
"""

import argparse
import csv
import sys
from pathlib import Path

import numpy as np

# Add src to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from emg_hand import calibration_tools, signal_analyzer


def load_rms_from_csv(csv_path: str) -> np.ndarray:
    """
    Load RMS values from a CSV file (assumes 'rms' column).

    Args:
        csv_path: Path to CSV file

    Returns:
        Array of RMS values
    """
    rms_vals = []
    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            if 'rms' in row:
                try:
                    rms_vals.append(float(row['rms']))
                except ValueError:
                    continue

    return np.array(rms_vals)


def main():
    parser = argparse.ArgumentParser(
        description="Calibrate gesture detection thresholds from EMG recordings"
    )
    parser.add_argument(
        "--resting",
        type=str,
        required=True,
        help="CSV file with resting EMG recording (processed RMS values)"
    )
    parser.add_argument(
        "--active",
        type=str,
        required=True,
        help="CSV file with active EMG recording (strong flexion)"
    )
    parser.add_argument(
        "--output-report",
        type=str,
        default="data/calibration_report.txt",
        help="Output file for calibration report"
    )
    parser.add_argument(
        "--output-header",
        type=str,
        default="data/calibration.h",
        help="Output Arduino header file with recommended constants"
    )
    parser.add_argument(
        "--fpr",
        type=float,
        default=0.05,
        help="Target false positive rate (false gestures while resting)"
    )
    parser.add_argument(
        "--fnr",
        type=float,
        default=0.05,
        help="Target false negative rate (missed activations)"
    )

    args = parser.parse_args()

    # Load data
    print("Loading calibration data...")
    rms_resting = load_rms_from_csv(args.resting)
    rms_active = load_rms_from_csv(args.active)

    if len(rms_resting) == 0 or len(rms_active) == 0:
        print("Error: Could not load RMS data from CSV files", file=sys.stderr)
        sys.exit(1)

    print(f"  Resting samples: {len(rms_resting)}")
    print(f"  Active samples: {len(rms_active)}")

    # Estimate thresholds
    print("\nEstimating optimal thresholds...")
    optimizer = calibration_tools.ThresholdOptimizer(rms_resting, rms_active)
    open_thresh, close_thresh = optimizer.find_optimal_thresholds(
        target_fpr=args.fpr,
        target_fnr=args.fnr
    )

    print(f"  Open threshold: {open_thresh:.2f}")
    print(f"  Close threshold: {close_thresh:.2f}")
    print(f"  Hysteresis: {close_thresh - open_thresh:.2f}")

    # Generate detailed report
    print(f"\nGenerating report...")
    report = calibration_tools.generate_calibration_report(
        rms_resting, rms_active, output_file=args.output_report
    )
    print(report)

    # Generate Arduino header file
    print(f"\nGenerating Arduino header...")
    header_content = f"""/**
 * Generated Calibration Constants
 * Auto-generated by calibrate_thresholds.py
 *
 * Parameters tuned for your specific electrode setup, skin impedance,
 * and muscle physiology. Review carefully before deployment.
 */

#ifndef CALIBRATION_H
#define CALIBRATION_H

// Gesture detection thresholds (RMS in ADC units or normalized)
const float CALIBRATION_OPEN_THRESHOLD = {open_thresh:.2f};
const float CALIBRATION_CLOSE_THRESHOLD = {close_thresh:.2f};

// Filter parameters (from standard values)
const int MA_WINDOW_SIZE = 32;
const float LP_FILTER_ALPHA = 0.1;

// Debounce timing
const unsigned long GESTURE_DEBOUNCE_MS = 500;
const int SERVO_SWEEP_TIME_MS = 300;

#endif  // CALIBRATION_H
"""

    output_header = Path(args.output_header)
    output_header.parent.mkdir(parents=True, exist_ok=True)
    with open(output_header, 'w') as f:
        f.write(header_content)

    print(f"[OK] Header written to {output_header}")

    # Summary statistics
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    print(f"Resting signal range: [{np.min(rms_resting):.2f}, {np.max(rms_resting):.2f}]")
    print(f"Active signal range:  [{np.min(rms_active):.2f}, {np.max(rms_active):.2f}]")
    print(f"\nEstimated false positive rate: {optimizer.false_positive_rate(open_thresh)*100:.1f}%")
    print(f"Estimated false negative rate: {optimizer.false_negative_rate(close_thresh)*100:.1f}%")
    print(f"\nNext step: Copy {output_header.name} into firmware/emg_hand/")


if __name__ == "__main__":
    main()
