import { chromium } from 'playwright';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell'});
const p=await b.newPage({viewport:{width:1440,height:900}});
const errs=[];p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message));
p.on('console',m=>{if(m.type()==='error'&&!m.text().includes('ERR_CONNECTION_RESET'))errs.push(m.text());});
await p.goto('http://localhost:4173/',{waitUntil:'load'});
await p.waitForTimeout(1200);
await p.screenshot({path:'/tmp/shots2/i-load.png',timeout:30000});
await p.waitForTimeout(14000);
const n=await p.evaluate(()=>document.querySelectorAll('.index-item').length);
const loaderGone=await p.evaluate(()=>document.querySelector('#loader').hidden);
console.log('index items:',n,'| loader hidden:',loaderGone);
await p.click('#ctl-index'); await p.waitForTimeout(2500);
await p.screenshot({path:'/tmp/shots2/i-index.png',animations:'disabled',timeout:60000});
// pick from the list
await p.evaluate(()=>document.querySelector('.index-item[data-id="mcu.esp32"]').click());
await p.waitForTimeout(5000);
const sel=await p.evaluate(()=>{const i=document.querySelector('#inspect');return i.hidden?null:document.querySelector('#inspect-title').textContent;});
console.log('list select ->',JSON.stringify(sel));
await p.screenshot({path:'/tmp/shots2/i-sel.png',animations:'disabled',timeout:60000});
console.log(errs.length?'ERRORS:\n'+errs.join('\n'):'no errors');
await b.close();
