import { chromium } from 'playwright';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell'});
const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const errs=[];p.on('pageerror',e=>errs.push('PAGEERROR: '+e.message));
await p.goto('http://localhost:4173/',{waitUntil:'load'});
await p.waitForTimeout(14000);
await p.screenshot({path:'/tmp/shots2/m-hero.png',animations:'disabled',timeout:60000});
await p.click('#ctl-index'); await p.waitForTimeout(2500);
await p.screenshot({path:'/tmp/shots2/m-index.png',animations:'disabled',timeout:60000});
await p.evaluate(()=>document.querySelector('.index-item[data-id="Majeure3"]').click());
await p.waitForTimeout(4000);
await p.screenshot({path:'/tmp/shots2/m-sel.png',animations:'disabled',timeout:60000});
const o=await p.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth);
console.log('overflow:',o);
console.log(errs.length?errs.join('\n'):'no errors');
await b.close();
