import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on('pageerror', (e) => errs.push('PAGEERROR: ' + e.message));
p.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
await p.goto('http://localhost:4180/', { waitUntil: 'load' });
await p.waitForTimeout(3000);
await p.screenshot({ path: '/tmp/shots/solo-hero.png' });
await p.evaluate(() => window.scrollTo(0, 3.2 * window.innerHeight));
await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/shots/solo-explode.png' });
await p.evaluate(() => document.querySelector('#parts').scrollIntoView({ block: 'start' }));
await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/shots/solo-parts.png' });
const canvases = await p.evaluate(() => document.querySelectorAll('canvas').length);
const webgl = await p.evaluate(() => !!document.querySelector('#hero-canvas').getContext('webgl2'));
console.log('canvases:', canvases, '| webgl ctx:', webgl);
console.log(errs.length ? 'ERRORS:\n' + errs.join('\n') : 'no errors');
await b.close();
