import { chromium } from 'playwright';
const t = process.argv[2] || '0';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell' });
const p = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
await p.goto(`http://localhost:5199/tune.html?t=${t}`,{waitUntil:'networkidle'});
await p.waitForFunction(()=>document.title==='READY',{timeout:30000}).catch(()=>console.log('TIMEOUT'));
await p.waitForTimeout(800);
await p.locator('#g').screenshot({path:`/tmp/shots2/tune-${t}.png`});
console.log(errs.length?'ERR:\n'+errs.join('\n'):'ok');
await b.close();
